# Generated by Django 5.2.1 on 2025-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_question_quiz_remove_quiz_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='ICT', max_length=50),
        ),
    ]
