# Generated by Django 5.2.1 on 2025-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
